[package]
name = "afs-tests"
version = "0.1.0"
edition = "2021"
description = "Structured generic compiler bench runner"
build = "build.rs"

[features]
default = ["linked-armfortas"]
linked-armfortas = []

[[bin]]
name = "afs-tests"
path = "src/main.rs"

[[bin]]
name = "bencch"
path = "src/bin/bencch.rs"

[dependencies]
bencch-core = { path = "../bench-core" }
armfortas = { path = "../.." }
