#!/usr/bin/env bash

set -euo pipefail

usage() {
    cat <<'EOF'
Usage: scripts/bootstrap-linked-armfortas.sh /path/to/armfortas [output-dir]

Generate a local bencch workspace that links against an external armfortas
checkout for linked capture.

Examples:
  scripts/bootstrap-linked-armfortas.sh ../armfortas
  scripts/bootstrap-linked-armfortas.sh /abs/path/to/armfortas .bencch-local
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

if [[ $# -lt 1 || $# -gt 2 ]]; then
    usage >&2
    exit 1
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
armfortas_root="${1}"
output_dir="${2:-${repo_root}/.bencch-local}"

if [[ ! -d "${armfortas_root}" ]]; then
    echo "armfortas checkout does not exist: ${armfortas_root}" >&2
    exit 1
fi

armfortas_root="$(cd "${armfortas_root}" && pwd)"
output_dir="$(mkdir -p "${output_dir}" && cd "${output_dir}" && pwd)"

if [[ ! -f "${armfortas_root}/Cargo.toml" ]]; then
    echo "armfortas checkout is missing Cargo.toml: ${armfortas_root}" >&2
    exit 1
fi

if [[ ! -d "${armfortas_root}/src" ]]; then
    echo "armfortas checkout is missing src/: ${armfortas_root}" >&2
    exit 1
fi

mkdir -p "${output_dir}/bench"

cat > "${output_dir}/Cargo.toml" <<EOF
# Generated by scripts/bootstrap-linked-armfortas.sh
[workspace]
members = ["bench"]
default-members = ["bench"]
resolver = "2"
EOF

cat > "${output_dir}/bench/Cargo.toml" <<EOF
# Generated by scripts/bootstrap-linked-armfortas.sh
[package]
name = "afs-tests"
version = "0.1.0"
edition = "2021"
description = "Structured generic compiler bench runner"

[lib]
path = "../../bench/src/lib.rs"

[[bin]]
name = "afs-tests"
path = "../../bench/src/main.rs"

[[bin]]
name = "bencch"
path = "../../bench/src/bin/bencch.rs"

[dependencies]
bencch-core = { path = "../../bench-core" }
armfortas = { path = "${armfortas_root}" }
EOF

cat > "${output_dir}/README.md" <<EOF
# Generated local workspace

This directory is generated by scripts/bootstrap-linked-armfortas.sh.

armfortas checkout: ${armfortas_root}

Use it with:

  cargo run --manifest-path "${output_dir}/Cargo.toml" -p afs-tests --bin bencch -- doctor
EOF

echo "Generated local workspace at ${output_dir}"
echo "Linked armfortas checkout: ${armfortas_root}"
echo
echo "Next step:"
echo "  cargo run --manifest-path \"${output_dir}/Cargo.toml\" -p afs-tests --bin bencch -- doctor"
