#!/usr/bin/env bash

set -euo pipefail

usage() {
    cat <<'EOF'
Usage: scripts/bootstrap-standalone-external.sh [output-dir]

Generate a local bencch workspace that builds without linked armfortas support.
This keeps compare/introspect/doctor available on the generic external-driver
surface.

Examples:
  scripts/bootstrap-standalone-external.sh
  scripts/bootstrap-standalone-external.sh .bencch-external
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

if [[ $# -gt 1 ]]; then
    usage >&2
    exit 1
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
output_dir="${1:-${repo_root}/.bencch-external}"
output_dir="$(mkdir -p "${output_dir}" && cd "${output_dir}" && pwd)"

mkdir -p "${output_dir}/bench"

cat > "${output_dir}/Cargo.toml" <<EOF
# Generated by scripts/bootstrap-standalone-external.sh
[workspace]
members = ["bench"]
default-members = ["bench"]
resolver = "2"
EOF

cat > "${output_dir}/bench/Cargo.toml" <<EOF
# Generated by scripts/bootstrap-standalone-external.sh
[package]
name = "afs-tests"
version = "0.1.0"
edition = "2021"
description = "Structured generic compiler bench runner"
build = "../../bench/build.rs"

[features]
default = []
linked-armfortas = []

[lib]
path = "../../bench/src/lib.rs"

[[bin]]
name = "afs-tests"
path = "../../bench/src/main.rs"

[[bin]]
name = "bencch"
path = "../../bench/src/bin/bencch.rs"

[dependencies]
bencch-core = { path = "../../bench-core" }
EOF

cat > "${output_dir}/README.md" <<EOF
# Generated external-only workspace

This directory is generated by scripts/bootstrap-standalone-external.sh.

It builds bencch without linked armfortas capture.

Use it with:

  cargo run --manifest-path "${output_dir}/Cargo.toml" -p afs-tests --bin bencch -- doctor
EOF

echo "Generated external-only workspace at ${output_dir}"
echo
echo "Next step:"
echo "  cargo run --manifest-path \"${output_dir}/Cargo.toml\" -p afs-tests --bin bencch -- doctor"
